[package]
name = "mancala_bot"
version = "0.1.0"
edition = "2021"

[dependencies]
egui = "0.20"
eframe = "0.20"
rand = "0.8"
static_assertions = "1.1"
ordered-float = "3.4"
itertools = "0.10"
arrayvec = "0.7"
ahash = "0.8"
num-format = "0.4"

# [profile.release]
# codegen-units = 1
# lto = true
